### ISSUE TITLE
Public Profile - Display Name + Country Not Saving

### ISSUE THREAD

**Issue by cameron1729** [DivinElegy/rock.divinelegy#9]
_From @dguzek on February 23, 2015 21:34_

On the live site, users are allowed to edit their *display name* and *country* under **My Arrows/Public Profile**.  Clicking *Save* notifies users that their details have been "Saved!" but it seems that the values are not, in fact, actually saved to the database.

It may also be worth noting that various JavaScript files on the production site still have `console.log` statements for debugging, but that probably isn't worth its own GitHub issue!

_Copied from original issue: DivinElegy/roll.divinelegy#8_

**Comment by dguzek** [comment]
I tried this out on the live site and it looks like it's fixed.  Thanks for the speedy response! :+1:
